# baseURL = "https://linuxhub-group.gitlab.io"
relativeURLs = true
languageCode = "zh-cn"
title = "Linuxhub"
theme = "github-style"
# googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  searchURL = "https://linuxhub-group.gitlab.io"
  author = "LinuxHub"
  description = "In solitude, where we are least alone."
  github = "LinuxHub-Group"
#   facebook = "MeiK2333"
#   twitter = "MeiK2333"
#   linkedin = "MeiK2333"
#   instagram = "MeiK2333"
#   tumblr = "MeiK2333"
#   email = "meik2333@gmail.com"
  url = "https://github.com/LinuxHub-Group"
  keywords = "blog"
  rss = true
  lastmod = true
  userStatusEmoji = "ðŸ¥µ"
  favicon = "images/github.png"
  location = "Japan"
  enableGitalk = false
  enableGiscus = true

  [params.giscus]
    repo = "LinuxHub-Group/linuxhub-group.github.io"
    repo_id = "R_kgDOIItJPA"
    category = "Show and tell"
    category_id = "DIC_kwDOIItJPM4CR1Sn"
    lang = "en"

#   [[params.links]]
#     title = "Link2"
#     href = "https://meik2333.com"
#     icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]